"""CLI command — mediakit init: generate default configuration."""

from __future__ import annotations

from pathlib import Path

import typer

app = typer.Typer()

# ---------------------------------------------------------------------------
# Config template
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
# ~/.mediakit/config.toml
# Generated by `mediakit init`. All values shown are defaults.

[general]
output_dir = "~/mediakit-output"       # default output directory for archive
date_format = "YYYY-MM-DD"             # filename date format
filename_max_length = 80               # max filename length

[summarize]
provider = "ollama"                    # "ollama" | "claude" | "openai" | "custom"
default_length = "medium"              # "small" | "medium" | "long"

[summarize.ollama]
model = "llama3.2"                     # any Ollama model name
host = "http://localhost:11434"        # Ollama server URL

[summarize.claude]
model = "claude-sonnet-4-20250514"    # Claude model ID
# API key via env: ANTHROPIC_API_KEY

[summarize.openai]
model = "gpt-4o"                       # OpenAI model ID
# API key via env: OPENAI_API_KEY

[summarize.custom]
endpoint = ""                          # custom OpenAI-compatible endpoint
model = ""
# API key via env: MEDIAKIT_LLM_API_KEY

[transcribe]
engine = "auto"                        # "auto" | "whisper" | "whisperx"
whisper_model = "base"                 # "tiny" | "base" | "small" | "medium" | "large"
diarize = false                        # speaker diarization (requires HF_TOKEN)
# HuggingFace token via env: HF_TOKEN

[scrape]
headless = true                        # run browser in headless mode
respect_robots = true                  # check robots.txt before scraping
rate_limit = 1.0                       # seconds between requests

[crawl]
max_depth = 10                         # max crawl depth for site mode
max_pages = 100                        # max pages to discover

[bot]
# Telegram token via env: TELEGRAM_BOT_TOKEN
whitelist_file = "~/.mediakit/whitelist.json"
preferences_file = "~/.mediakit/preferences.json"
"""


@app.command()
def init() -> None:
    """Generate ~/.mediakit/config.toml with commented defaults."""

    config_dir = Path("~/.mediakit").expanduser()
    config_path = config_dir / "config.toml"

    # If the file already exists, ask before overwriting.
    if config_path.exists():
        overwrite = typer.confirm(
            f"{config_path} already exists. Overwrite?", default=False
        )
        if not overwrite:
            typer.echo("Aborted.")
            raise typer.Exit()

    # Create directory if needed.
    config_dir.mkdir(parents=True, exist_ok=True)

    # Write the template.
    config_path.write_text(_CONFIG_TEMPLATE, encoding="utf-8")

    typer.echo(f"Config written to {config_path}")


if __name__ == "__main__":
    app()
