"""CLI command — readpile init: generate default configuration."""

from __future__ import annotations

from pathlib import Path

import typer

app = typer.Typer()

_CONFIG_TEMPLATE = """\
# ~/.readpile/config.toml
# Generated by `readpile init`. All values shown are defaults.

[general]
output_dir = "{output_dir}"
auto_archive = {auto_archive}
date_format = "YYYY-MM-DD"
filename_max_length = 80

[transcribe]
engine = "auto"
whisper_model = "base"
diarize = false
# HuggingFace token via env: HF_TOKEN
# YouTube cookies for bypassing IP bans (see README for setup):
# youtube_cookies = "~/.readpile/youtube-cookies.txt"

[scrape]
headless = true
respect_robots = true
rate_limit = 1.0

[crawl]
max_depth = 10
max_pages = 100

[bot]
# Telegram token via env: TELEGRAM_BOT_TOKEN
whitelist_file = "~/.readpile/whitelist.json"
preferences_file = "~/.readpile/preferences.json"
"""


@app.command()
def init() -> None:
    """Generate ~/.readpile/config.toml with defaults."""

    config_dir = Path("~/.readpile").expanduser()
    config_path = config_dir / "config.toml"

    if config_path.exists():
        overwrite = typer.confirm(
            f"{config_path} already exists. Overwrite?", default=False
        )
        if not overwrite:
            typer.echo("Aborted.")
            raise typer.Exit()

    auto_archive = typer.confirm(
        "Archive extracted content to disk by default?", default=False
    )
    output_dir = typer.prompt(
        "Output directory (when archiving)", default="~/readpile-output"
    )

    config_dir.mkdir(parents=True, exist_ok=True)

    content = _CONFIG_TEMPLATE.format(
        output_dir=output_dir,
        auto_archive=str(auto_archive).lower(),
    )
    config_path.write_text(content, encoding="utf-8")

    typer.echo(f"Config written to {config_path}")


if __name__ == "__main__":
    app()
