"""CLI command — readpile init: generate default configuration."""

from __future__ import annotations

from pathlib import Path

import typer

app = typer.Typer()

_CONFIG_TEMPLATE = """\
# ~/.readpile/config.toml
# Generated by `readpile init`. Re-run `readpile init` to regenerate.

[general]
output_dir = "{output_dir}"
auto_archive = {auto_archive}
date_format = "YYYY-MM-DD"
filename_max_length = 80

[transcribe]
engine = "auto"
whisper_model = "{whisper_model}"
diarize = false
# HuggingFace token via env: HF_TOKEN
# YouTube cookies for bypassing IP bans (see README for setup):
# youtube_cookies = "~/.readpile/youtube-cookies.txt"

[scrape]
headless = true
respect_robots = true
rate_limit = 1.0

[crawl]
max_depth = 10
max_pages = 100

[wiki]
default_dir = "{wiki_dir}"
"""

_LLM_TEMPLATE = """\

[llm]
provider = "{llm_provider}"
model = "{llm_model}"
# API key via env: READPILE_LLM_API_KEY
"""

_SYNC_TEMPLATE = """\

[sync]
state_file = "~/.readpile/sync-state.json"
log_file = "~/.readpile/sync.log"
synthesis_wait_days = 7
max_auto_synthesize_per_run = 20
max_initial_entries = 20
max_consecutive_failures = 7

[sync.email]
enabled = {email_enabled}
provider = "{email_provider}"
account = "{email_account}"
credentials_file = "~/.readpile/email-credentials.json"
labels = ["INBOX"]
max_age_days = 7
skip_synthesis_senders = []

[sync.digest]
enabled = {digest_enabled}
to = "{digest_to}"
from = "{digest_from}"
smtp_host = "smtp.gmail.com"
smtp_port = 587
max_topic_files = 5
max_pending_digests = 7
wiki_health_day = "saturday"
# SMTP password via env: READPILE_SMTP_PASSWORD
"""

_LLM_MODELS = {
    "claude": "claude-sonnet-4-6",
    "openai": "gpt-4o",
    "ollama": "llama3",
}


@app.command()
def init() -> None:
    """Generate ~/.readpile/config.toml with defaults.

    Run this again at any time to regenerate your config.
    """

    config_dir = Path("~/.readpile").expanduser()
    config_path = config_dir / "config.toml"

    if config_path.exists():
        overwrite = typer.confirm(
            f"{config_path} already exists. Overwrite?", default=False
        )
        if not overwrite:
            typer.echo("Aborted.")
            raise typer.Exit()

    typer.echo("")
    typer.echo("─── General ───")
    typer.echo("")

    auto_archive = typer.confirm(
        "Archive extracted content to disk by default?", default=False
    )
    output_dir = typer.prompt(
        "Output directory (when archiving)", default="~/readpile-output"
    )
    whisper_model = typer.prompt(
        "Whisper model for podcast transcription (medium/large)",
        default="medium",
    )

    typer.echo("")
    typer.echo("─── Wiki ───")
    typer.echo("")

    wiki_dir = typer.prompt(
        "Wiki directory", default="~/my-wiki"
    )

    typer.echo("")
    typer.echo("─── LLM Provider ───")
    typer.echo("  Used by the sync pipeline for digest grouping and wiki synthesis.")
    typer.echo("  Not needed for content extraction (scrape, transcribe, crawl).")
    typer.echo("")

    llm_provider = typer.prompt(
        "LLM provider (claude/openai/ollama)",
        default="claude",
    )
    llm_model = _LLM_MODELS.get(llm_provider, "claude-sonnet-4-6")

    typer.echo("")
    typer.echo("─── Email & Digest ───")
    typer.echo("  Optional. Enables automated content collection from a dedicated email")
    typer.echo("  inbox and daily digest delivery. If you skip this, you can still use")
    typer.echo("  readpile manually (scrape, transcribe, wiki tools, MCP) — you just")
    typer.echo("  won't get the email-driven sync pipeline.")
    typer.echo("")

    email_enabled = typer.confirm(
        "Enable email collection and daily digests?", default=False
    )
    email_account = ""
    digest_to = ""
    digest_from = ""

    if email_enabled:
        email_account = typer.prompt(
            "Readpile email (a dedicated inbox that receives your newsletters)",
            default="readpile-inbox@gmail.com",
        )
        digest_to = typer.prompt(
            "Your personal email (where readpile sends daily digests)"
        )
        digest_from = email_account

    # --- Build config ---

    config_dir.mkdir(parents=True, exist_ok=True)
    import os, stat
    try:
        os.chmod(config_dir, stat.S_IRWXU)
    except OSError:
        pass

    content = _CONFIG_TEMPLATE.format(
        output_dir=output_dir,
        auto_archive=str(auto_archive).lower(),
        whisper_model=whisper_model,
        wiki_dir=wiki_dir,
    )

    content += _LLM_TEMPLATE.format(llm_provider=llm_provider, llm_model=llm_model)

    content += _SYNC_TEMPLATE.format(
        email_enabled=str(email_enabled).lower(),
        email_provider="gmail" if email_enabled else "gmail",
        email_account=email_account,
        digest_enabled=str(email_enabled).lower(),
        digest_to=digest_to,
        digest_from=digest_from,
    )

    config_path.write_text(content, encoding="utf-8")

    sources_path = config_dir / "sources.toml"
    if not sources_path.exists():
        sources_path.write_text("# Feed sources — managed by `readpile sources`\n", encoding="utf-8")

    # --- Next steps ---

    typer.echo("")
    typer.echo(f"Config written to {config_path}")
    typer.echo("")
    typer.echo("─── Next Steps ───")
    typer.echo("")

    env_vars: list[str] = []

    typer.echo("1. Create your wiki:")
    typer.echo(f"     readpile wiki init {wiki_dir}")
    typer.echo("")

    if llm_provider != "ollama":
        provider_name = "Anthropic" if llm_provider == "claude" else "OpenAI"
        env_vars.append(f"  export READPILE_LLM_API_KEY='your-{llm_provider}-api-key'")
        typer.echo(f"2. Set your {provider_name} API key (for sync pipeline):")
        typer.echo(f"     export READPILE_LLM_API_KEY='your-{llm_provider}-api-key'")
        typer.echo("")

    if email_enabled:
        env_vars.append(f"  export READPILE_SMTP_PASSWORD='your-gmail-app-password'")
        typer.echo(
            f"3. Set up email sending (for digests from {email_account}):"
        )
        typer.echo(f"     a. Enable 2FA on the {email_account} Google account")
        typer.echo(f"     b. Generate an App Password: Google Account → Security → App Passwords")
        typer.echo(f"     c. Set the env var (paste the 16 characters with or without spaces):")
        typer.echo(f"          export READPILE_SMTP_PASSWORD='abcdefghijklmnop'")
        typer.echo("")
        typer.echo(
            f"4. Set up email reading (for inbox collection from {email_account}):"
        )
        typer.echo(f"     See the 'Gmail OAuth setup' section in README.md for a step-by-step guide.")
        typer.echo("")

    if env_vars:
        typer.echo("  Add to your shell profile (~/.zshrc or ~/.bashrc) to persist:")
        for var in env_vars:
            typer.echo(f"  {var}")
        typer.echo("")

    typer.echo("You can re-run `readpile init` at any time to regenerate this config.")


if __name__ == "__main__":
    app()
