"""CLI command — readpile init: generate default configuration."""

from __future__ import annotations

from pathlib import Path

import typer

app = typer.Typer()

_CONFIG_TEMPLATE = """\
# ~/.readpile/config.toml
# Generated by `readpile init`. Re-run `readpile init` to regenerate.

[general]
date_format = "YYYY-MM-DD"
filename_max_length = 80

[transcribe]
engine = "auto"
whisper_model = "{whisper_model}"
diarize = false
# HuggingFace token for optional speaker diarization:
hf_token = "{hf_token}"
# YouTube cookies for bypassing IP bans (see README for setup):
# youtube_cookies = "~/.readpile/youtube-cookies.txt"

[scrape]
headless = true
respect_robots = true
rate_limit = 1.0

[crawl]
max_depth = 10
max_pages = 100

[wiki]
default_dir = "{wiki_dir}"
"""

_LLM_TEMPLATE = """\

[llm]
base_url = "{llm_base_url}"
model = "{llm_model}"
api_key = "{llm_api_key}"
"""

_SYNC_TEMPLATE = """\

[sync]
state_file = "~/.readpile/sync-state.json"
log_file = "~/.readpile/sync.log"
synthesis_wait_days = 7
max_auto_synthesize_per_run = 20
max_initial_entries = 20
max_consecutive_failures = 7

[sync.email]
enabled = {email_enabled}
provider = "{email_provider}"
account = "{email_account}"
credentials_file = "~/.readpile/email-credentials.json"
labels = ["INBOX"]
max_age_days = 7
trusted_senders = []

[sync.digest]
enabled = {digest_enabled}
to = "{digest_to}"
from = "{digest_from}"
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_password = "{smtp_password}"
max_topic_files = 5
max_pending_digests = 7
wiki_health_day = "saturday"
"""

_LLM_PRESETS: dict[str, tuple[str, str]] = {
    "anthropic": ("anthropic", "claude-sonnet-4-6"),
    "openai": ("", "gpt-4o"),
    "gemini": ("gemini", "gemini-2.0-flash"),
    "openrouter": ("openrouter", ""),
    "ollama": ("ollama", "llama3"),
}


@app.command()
def init() -> None:
    """Generate ~/.readpile/config.toml with defaults.

    Run this again at any time to regenerate your config.
    """

    config_dir = Path("~/.readpile").expanduser()
    config_path = config_dir / "config.toml"

    if config_path.exists():
        overwrite = typer.confirm(
            f"{config_path} already exists. Overwrite?", default=False
        )
        if not overwrite:
            typer.echo("Aborted.")
            raise typer.Exit()

    typer.echo("")
    typer.echo("─── General ───")
    typer.echo("")

    whisper_model = typer.prompt(
        "Whisper model for podcast transcription (medium/large)",
        default="medium",
    )

    typer.echo("  (Optional) HuggingFace token for speaker diarization (speaker ID).")
    typer.echo("  Required only for whisperx with 'diarize = true'.")
    hf_token = typer.prompt(
        "HuggingFace token", default="", show_default=False
    )

    typer.echo("")
    typer.echo("─── Wiki ───")
    typer.echo("")

    wiki_dir = typer.prompt(
        "Wiki directory", default="~/my-wiki"
    )
    wiki_name = typer.prompt(
        "Wiki name", default="My Wiki"
    )

    typer.echo("")
    typer.echo("─── LLM ───")
    typer.echo("  Used by the sync pipeline for digest grouping and wiki synthesis.")
    typer.echo("  Not needed for content extraction (scrape, transcribe, crawl).")
    typer.echo("  Any OpenAI-compatible API works. Shortcuts: anthropic, openai, gemini, openrouter, ollama")
    typer.echo("")

    llm_base_url = typer.prompt(
        "LLM base_url (shortcut name or full URL)",
        default="anthropic",
    )
    preset = _LLM_PRESETS.get(llm_base_url)
    default_model = preset[1] if preset else ""
    llm_model = typer.prompt(
        "Model name",
        default=default_model or "claude-sonnet-4-6",
    )

    llm_api_key = ""
    if llm_base_url != "ollama" and not llm_base_url.startswith("http://localhost"):
        llm_api_key = typer.prompt("LLM API Key")

    typer.echo("")
    typer.echo("─── Email & Digest ───")
    typer.echo("  Optional. Enables automated content collection from a dedicated email")
    typer.echo("  inbox and daily digest delivery. If you skip this, you can still use")
    typer.echo("  readpile manually (scrape, transcribe, wiki tools, MCP) — you just")
    typer.echo("  won't get the email-driven sync pipeline.")
    typer.echo("")

    email_enabled = typer.confirm(
        "Enable email collection and daily digests?", default=False
    )
    email_account = ""
    digest_to = ""
    digest_from = ""
    smtp_password = ""

    if email_enabled:
        email_account = typer.prompt(
            "Readpile email (a dedicated inbox that receives your newsletters)",
            default="readpile-inbox@gmail.com",
        )
        digest_to = typer.prompt(
            "Your personal email (where readpile sends daily digests)"
        )
        digest_from = email_account
        typer.echo("  To send digests, readpile needs a Gmail App Password for the inbox.")
        typer.echo("  Generate one at: Google Account -> Security -> App Passwords")
        smtp_password = typer.prompt("Gmail App Password")

    # --- Build config ---

    config_dir.mkdir(parents=True, exist_ok=True)
    import os, stat
    try:
        os.chmod(config_dir, stat.S_IRWXU)
    except OSError:
        pass

    content = _CONFIG_TEMPLATE.format(
        whisper_model=whisper_model,
        hf_token=hf_token,
        wiki_dir=wiki_dir,
    )

    content += _LLM_TEMPLATE.format(
        llm_base_url=llm_base_url,
        llm_model=llm_model,
        llm_api_key=llm_api_key,
    )

    content += _SYNC_TEMPLATE.format(
        email_enabled=str(email_enabled).lower(),
        email_provider="gmail" if email_enabled else "gmail",
        email_account=email_account,
        digest_enabled=str(email_enabled).lower(),
        digest_to=digest_to,
        digest_from=digest_from,
        smtp_password=smtp_password,
    )

    config_path.write_text(content, encoding="utf-8")
    try:
        os.chmod(config_path, stat.S_IRUSR | stat.S_IWUSR)  # 600
    except OSError:
        pass

    feeds_path = config_dir / "feeds.toml"
    if not feeds_path.exists():
        feeds_path.write_text("# Feed subscriptions — managed by `readpile feeds`\n", encoding="utf-8")

    # --- Create wiki ---

    from readpile.wiki import WikiStore

    wiki_path = Path(wiki_dir).expanduser().resolve()
    if (wiki_path / ".wiki.toml").exists():
        typer.echo(f"Wiki already exists at {wiki_path}, skipping creation.")
    else:
        store = WikiStore(wiki_dir)
        store.init(name=wiki_name)
        typer.echo(f"Wiki created at {wiki_path}")

    # --- Next steps ---

    typer.echo("")
    typer.echo(f"Config written to {config_path} (permissions: 600)")
    typer.echo("")
    typer.echo("─── Next Steps ───")
    typer.echo("")

    step = 1

    if email_enabled:
        typer.echo(
            f"{step}. Set up email reading (for inbox collection from {email_account}):"
        )
        typer.echo(f"     See the 'Gmail OAuth setup' section in README.md for a step-by-step guide.")
        typer.echo("")
        step += 1

    typer.echo(f"{step}. Add your first feeds:")
    typer.echo("     readpile feeds add 'https://example.com/blog'")
    typer.echo("")

    typer.echo("You can re-run `readpile init` at any time to update your configuration.")


if __name__ == "__main__":
    app()
